menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'presentations', url: '/presentations'}
- {name: 'cv', url: '/cv'}
- {name: 'about', url: '/about'}

about:

courses:

social:
- {icon: 'github', link: 'https://github.com/yagmurkiper'}
- {icon: 'scholar', link: 'https://scholar.google.com/citations?user=_4wll80AAAAJ&hl=en&oi=ao'}
- {icon: 'linkedin', link: 'www.linkedin.com/in/yagmur-kiper'}

presentations:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
